# Generated by Django 4.2.7 on 2024-01-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='badge',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
